### ISSUE TITLE
Wrong Titles for panels?

### ISSUE THREAD

**Issue by Vivybestwaifu** [kingToolbox/DIGEdit#10]
The name of the Filter panel seems to be "Explorer" while the name of the "Explorer" panel seems to be "Filer" (it's also a typo I guess).
![image](https://user-images.githubusercontent.com/88204765/127704639-56413c12-a382-4450-9f0c-59207b045184.png)

**Comment by kingToolbox** [comment]
Thank you. Both of these words can be used to name the file manager. It's just that `Filer` was first used when developing `SFTP/SCP`, and then when the active file manager needed to be named, I couldn't think of a suitable name for a while, so I borrowed from VSCode, and its active file manager is `Explorer`, so I used this word. 

Because changing the name is not just a simple change of the string. All related classes and configuration files need to be modified, so there is no plan to modify this, please understand. 

To say something off topic, I think the word `Filer` is what I need, there is a plan to develop a file manager and the name is just called `WindFiler`. Most file managers are either called `Explorer` such as `Xplorer2` or `Commander` such as `Total Commander`, `Double Commander`, and I didn't want to use these two words, I think they both contain too many characters, so I chose `Filer` at the beginning.

There are also some products that choose to use the word `Filer`, such as `ROX-Filer` for x11 and so on.

**Comment by Vivybestwaifu** [comment]
Thank you for your response and explanation. This helps a alot.

**Comment by kingToolbox** [comment]
You are welcome. :smile:
